'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basicDaggerL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basicDaggerL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basicDaggerR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basicDaggerR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bgmusicGreen() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bgmusicGreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bracer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bracer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnChaIn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnChaIn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnInv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnInv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gloves() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gloves", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobAttR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobAttR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobDeathR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobDeathR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobHitL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobHitL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobHitR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobHitR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobIdleL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobIdleL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobIdleR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobIdleR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goblinAttack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goblinAttack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goblinBattleIdle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goblinBattleIdle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goblinDeath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goblinDeath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gobWalkR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gobWalkR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grasslandDungeonBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grasslandDungeonBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Helm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Helm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Legs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Legs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magAttR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magAttR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mageBattleStance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mageBattleStance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magFlyR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magFlyR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magIdleL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magIdleL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magIdleR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magIdleR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogAttR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogAttR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogHitR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogHitR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogIdleL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogIdleL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogIdleR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogIdleR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogueBaseAttack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogueBaseAttack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogueBattleStanceL25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogueBattleStanceL25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogueBattleStanceN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogueBattleStanceN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rogWalkR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rogWalkR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shstagewaterfall084slow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shstagewaterfall084slow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SwordL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SwordL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SwordR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SwordR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property test() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("test", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TestGif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TestGif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TestWalking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TestWalking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TitleScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TitleScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TitleScreenN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TitleScreenN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warAttR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warAttR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warIdleL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warIdleL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warIdleR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warIdleR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warriorBattleStance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warriorBattleStance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkL2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkL2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkL3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkL3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkL4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkL4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warWalkR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warWalkR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property waterfallAmbient() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("waterfallAmbient", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
